# Generated by Django 3.2 on 2021-04-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='description',
            field=models.CharField(default='a wish', max_length=255),
            preserve_default=False,
        ),
    ]
