# Generated by Django 3.2 on 2021-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_wish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted_for',
            field=models.ManyToManyField(related_name='granted_wish', to='exam_app.User'),
        ),
    ]
